MOOC-1268 Feat: add wcag accessibility success reset password
OPI-PIB/navoica-platform pull request #287
Opened 2020-09-24 10:00 UTC by paula-opi

Added for success message rest password accessibility for screen readers.

2020-09-29 13:10 UTC, krystianlygas requested changes

2020-09-29 13:10 UTC, krystianlygas commented on lms/templates/forgot_password_modal.html
>                      $('#pwd_reset_form').prepend('<div id="pwd_error" class="modal-form-error">${_("Email is incorrect.")}</div>');
zgubiony ${} - nie tłumaczy

2020-09-29 13:10 UTC, krystianlygas commented on lms/templates/forgot_password_modal.html
>          if (emailPatternValidation.test(emailValue)) {
walidacja już dzieje się po html5, więc testowanie regexa jest niepotrzebna

2020-09-30 06:55 UTC, paula-opi commented on lms/templates/forgot_password_modal.html
>                      $('#pwd_reset_form').prepend('<div id="pwd_error" class="modal-form-error">${_("Email is incorrect.")}</div>');
Dodane

2020-09-30 12:52 UTC, krystianlygas approved these changes
Wydaje mi się że input required by wystarczył. No ale ok - działa

2020-09-30 12:52 UTC, merged