Feature/mooc 1230
OPI-PIB/navoica-platform pull request #289
Opened 2020-09-24 10:15 UTC by paula-opi

2020-09-28 14:33 UTC, krystianlygas requested changes
Zgubiłaś w kilku miejscach ${} , oczywiście wstaw je wewnątrz stringów "${}"

2020-09-28 14:33 UTC, krystianlygas commented on lms/templates/register.html
> +                                    let confirmPasswordTranslation = _('A valid confirm password is required');
"${}"

2020-09-29 08:47 UTC, paula-opi commented on lms/templates/register.html
> +                message: _('A properly formatted e-mail is required'),
Uzupełnione

2020-09-29 08:47 UTC, paula-opi commented on lms/templates/register.html
> +                field: _('E-mail'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                message: _('Your legal name must be a minimum of two characters long'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                field: _('Full Name'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                message: _('Usernames can only contain letters (A-Z, a-z), numerals (0-9), underscores (_), and hyphens (-) and must be between 2 and 255 characters long.'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                field: _('Terms of Service'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                message: _('To enroll, you must follow the honor code.'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                message: _('To enroll, you must follow the honor code.'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                field: _('Honor Code'),
Uzupełnione

2020-09-29 08:48 UTC, paula-opi commented on lms/templates/register.html
> +                                    let confirmPasswordTranslation = _('A valid confirm password is required');
Uzupełnione

2020-09-29 11:55 UTC, krystianlygas requested changes
Gdy gettextujesz frazy ${}, to powinnaś wyekstraktować źródła i dodać je do commitu.

2020-09-30 13:15 UTC, krystianlygas approved these changes
Zatwierdzam

2020-09-30 13:15 UTC, merged