MOOC-1318 Fix: change error message text
OPI-PIB/navoica-platform pull request #354
Opened 2020-10-09 15:33 UTC by kaczmarczyk-malgorzata

translation

2020-10-12 09:42 UTC, krystianlygas requested changes

2020-10-12 09:42 UTC, krystianlygas commented on conf/locale/en/LC_MESSAGES/django.po
> -"POT-Creation-Date: 2020-08-19 12:54+0000\n"
Nie commitujemy pliku django.po

2020-10-14 07:13 UTC, kaczmarczyk-malgorzata commented on conf/locale/en/LC_MESSAGES/django.po
> -"POT-Creation-Date: 2020-08-19 12:54+0000\n"
@krystianlygas poprawione

2020-10-14 07:58 UTC, krystianlygas approved these changes

2020-10-14 07:59 UTC, merged