MOOC-1403 Fix: add progress bar update
OPI-PIB/navoica-platform pull request #373
Opened 2020-10-20 11:38 UTC by paula-opi

Added update progress bar on submit answer and fired request on course page.

2020-10-20 15:12 UTC, krystianlygas requested changes
Zadanie nie spełnia punktu 1 i 2 z Jira. 
Tak wygląda konsola dla url'u /dashboard
![image](https://user-images.githubusercontent.com/51002868/96606190-4a6fe000-12f7-11eb-80df-0c375c1da217.png)

Robione są requesty w miejscach gdzie nie powinny. W poprzednim komentarzu (Jira) opisałem problem.

2020-10-21 06:08 UTC, paula-opi commented
> Zadanie nie spełnia punktu 1 i 2 z Jira.
> Tak wygląda konsola dla url'u /dashboard
> ![image](https://user-images.githubusercontent.com/51002868/96606190-4a6fe000-12f7-11eb-80df-0c375c1da217.png)
> 
> Robione są requesty w miejscach gdzie nie powinny. W poprzednim komentarzu (Jira) opisałem problem.

Proszę wyczyśc cache i wygeneruj na nowo assety i odśwież stronę, bo nigdzie nie wywołuje się GET progress poza stroną na zapisanym kursie.

2020-10-21 07:51 UTC, krystianlygas commented
Rzeczywiście, generowałem i resetowałem. Ale jak widać coś poszło po drodze nie tak. 
To popraw jeszcze url:
![image](https://user-images.githubusercontent.com/51002868/96686863-64ed9c00-137f-11eb-8582-4deecc367c73.png)
bo w tej chwili jest robiony redirecting z racji braku '/' na końcu linii. 
No i ten course_info wczytywany jest nadal do każdej strony. Dodałaś warunek aby nie wyzwalał się na każdej podstronie, ale po co ładować coś wszędzie jeśli nie jest wszędzie wykorzystywane?
![image](https://user-images.githubusercontent.com/51002868/96687569-6370a380-1380-11eb-8102-29553f907a93.png)
Przykład /dashboardu:
![image](https://user-images.githubusercontent.com/51002868/96687734-961a9c00-1380-11eb-9f1a-d8a0ce1d1c35.png)
Wystarczy tę linię:
https://github.com/OPI-PIB/navoica-platform/blob/057c4b2d2c5be0c12b5a68357aa03c95962ec4c9/lms/templates/preview_menu.html#L21
Przerobić na:
![image](https://user-images.githubusercontent.com/51002868/96689598-ea268000-1382-11eb-9d6a-40beb6cf4988.png)

2020-10-21 12:41 UTC, paula-opi commented
Zmieniłam import skryptu javascript dla progress bar na webpack module i doałam na końcu api url '/'

2020-10-22 09:53 UTC, merged