MOOC-1553 500/404 h1 fixes
OPI-PIB/navoica-platform pull request #464
Opened 2021-01-27 16:47 UTC by makarun

2021-01-27 16:48 UTC, makarun commented
https://jira.opi.org.pl/browse/MOOC-1553

2021-01-29 10:57 UTC, paula-opi requested changes
@makarun proszę popraw te drobiazgi.

2021-01-29 17:32 UTC, AgataSkie commented
Nowy projekt Agaty wprowadza jeszcze jedną zmianę, kiedy na górze jest widoczne "404/500" to w treści nie ma już "Error 404/500"

2021-01-29 17:37 UTC, AgataSkie commented
Obraz na podstronie 500 ma niepoprawny alt="500 image". Poprawnie będzie alt="" ewentualnie można by było opisać alt="Człowiek podchodzi do komputera z młotkiem", ale nie "500 image". Pusty alt też jak najbardziej ok, tak masz zresztą w 404.

2021-02-02 13:44 UTC, paula-opi approved these changes

2021-02-02 14:26 UTC, AgataSkie approved these changes

2021-02-02 15:04 UTC, merged