MOOC-1819 Fix: add fixed styles forgotten password and scroll to erro…
OPI-PIB/navoica-platform pull request #486
Opened 2021-02-11 14:31 UTC by paula-opi

…r field on submit on register

2021-02-12 09:43 UTC, AgataSkie reviewed
nie potrafię przetestować poprawionych styli przycisków na oauth/confirm, bo na localhost nie potrafie jak podpiać formularzu do kursu, proszę kogoś o potwierdzenie, że problem już nie wystepuje.
Pozostałe zmiany przetestowałam lokalnie i jest ok.

2021-02-14 22:00 UTC, hoffmannkrzysztof requested changes
Problem ze scrollowaniem występuje nadal. Problem z wygenerowanym hasłem z lastpass. Opisane w issue na jirze ze screenem. Reszta wygląda ok

2021-02-15 07:18 UTC, paula-opi commented
> Problem ze scrollowaniem występuje nadal. Problem z wygenerowanym hasłem z lastpass. Opisane w issue na jirze ze screenem. Reszta wygląda ok

Zdecydowaliśmy o scrollu do miejsca błędu, nie do góry strony. Nie zostało to zawarte w opisie zadania chyba, że taka decyzja padła. Błąd polegał na tym że scrollowało zawsze to góry ale nie było widać alertu/bannera.

Co do hasła, nie zgłaszano takiego problemu, sprawdzę to.

2021-02-15 15:05 UTC, krystianlygas commented
Mi nie działa. Szczegóły zawarłem w jira. Poza tym ten PR powinien być zrobiony do hotfixa, jeżeli te zmiany mają się pojawić priorytetowo na produkcji.

2021-02-16 07:30 UTC, paula-opi commented
@krystianlygas 
Dzięki za sprawdzenia. U mnie akurat nie występuję ten błąd, ale przeanalizowałam i dodałam małą poprawkę w tym miejscu, ciekawe, że mimo podwójnej deklaracji selektora $() u mnie nie wysypało się. Pull request jest jako feature, nikt nie zgłaszał jako hotfixa.

2021-02-16 08:57 UTC, merged