MOOC-1898 Feat: add new footer and navbar header
OPI-PIB/navoica-platform pull request #521
Opened 2021-03-30 13:55 UTC by paula-opi

2021-04-01 16:24 UTC, AgataSkie commented
zamiesciłam uwagi w jira

2021-04-02 12:35 UTC, AgataSkie requested changes
uwagi w załączniku w jira

2021-04-06 13:11 UTC, paula-opi commented
> uwagi w załączniku w jira

1. dla mobilnej wersji nie mamy searcha na ten moment zaprojektowanego, Agata W. zrobiła poglądowo tylko ikonkę, ale nie implementujemy.
2. na scroll jest dodawany box-shadow do navbaru, jeśli to miałaś na myśli w zmianie wyglądu

2021-04-07 16:41 UTC, AgataSkie commented
Jest już całkiem spoko, jeszcze coś znalazłam i zamieściłam w jira.

2021-04-12 14:04 UTC, merged